apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    system: overseer
  name: overseer
spec:
  replicas: 1
  selector:
    matchLabels:
      system: overseer
  template:
    metadata:
      labels:
        system: overseer
    spec:
      containers:
        # - command:
        #     - "/bin/sh"
        #   args:
        #     - /workspace/overseer/startup/start.sh
        - image: "{{ .Values.overseer.image.repository }}:{{ .Values.overseer.image.tag }}"
          imagePullPolicy: IfNotPresent
          name: overseer
          ports:
            - containerPort: 8443
              name: overseer-port
              protocol: TCP
      #     volumeMounts:
      #       - mountPath: /workspace
      #         name: workspace
      # volumes:
      #   - hostPath:
      #       path: "{{ .Values.workspace }}"
      #       type: Directory
      #     name: workspace
